# vlan_id @ #
#------------#
vlan_id_1: 10
vlan_id_2: 20
vlan_id_3: 30
vlan_id_4: 40

# vlan_name @ #
#------------#
vlan_name_1: LAN
vlan_name_2: WIFI
vlan_name_3: VOICE
vlan_name_4: INTERCO

provider:
  host: "{{ inventory_hostname }}"
  username: "{{ mgmt_username }}"
  password: "{{ mgmt_password }}"

ospf_vlan_1_imask: 0.0.0.127
ospf_vlan_2_imask: 0.0.0.31
ospf_vlan_3_imask: 0.0.0.31
ospf_vlan_4_imask: 0.0.0.15

eth_vlan_1_mask: 255.255.255.128
eth_vlan_2_mask: 255.255.255.224
eth_vlan_3_mask: 255.255.255.224
eth_vlan_4_mask: 255.255.255.240
