# Credentials #
#-------------#
mgmt_username: cisco
mgmt_password: cisco

eth_01_id: 0/1
eth_01_description: interco rtr-switch
eth_01_mask: 255.255.255.240

eth_02_id: 0/2
eth_02_description: WAN for DMVPN
eth_02_mask: 255.255.255.0

ospf_process_number: 1
ospf_dmvpn_network: 172.16.0.0
ospf_loop_imask: 0.0.0.0
ospf_interco_imask: 0.0.0.15
ospf_dmvpn_imask: 0.0.0.255

loop_number: 1
loop_mask: 255.255.255.255

interface_spoke_dmvpn: Tunnel1
description_spoke_dmvpn: HOST DYNAMIC TUNNEL
bandwidth_spoke_dmvpn: 1000
net_mask_spoke_dmvpn: 255.255.255.0
nhrp_map_ip_spoke_dmvpn: 172.16.0.1
nhrp_network_id_spoke_dmvpn: 99
nhrp_holdtime_spoke_dmvpn: 300
nhrp_nhs_ip_spoke_dmvpn: 172.16.0.1
tunnel_source_spoke_dmvpn: e0/2
tunnel_key_spoke_dmvpn: 100000
tunnel_ipsec_profile_spoke_dmvpn: dmvpnprof
nhrp_map_ip_multicast_spoke_dmvpn: 170.254.0.1


# CRYPTO IPSEC @ #
#----------------#
crypto_ipsec_name: dmvpnprof
group_number_crypto_policy: 2
authentication_type_crypto_policy: pre-share
id_crypto_policy: 5
crypto_isakmp_transform_set: dmvpnset
