# Configuration ccnp
---
- hosts: ios_router_bordeaux
  gather_facts: no
  connection: local
  roles:
    - { role: 0_ios_router_network_interfaces }
    - { role: 1_ios_router_osfp }
    - { role: 2_ios_router_hub_dmvpn}