# Configuration ccnp
---
- hosts: router
  connection: local
  roles:
     - { role: router_network_interfaces }
     - { role: router_ospf }
     - { role: router_ipsec_vpn }

- hosts: DMVPN_HUB
  connection: local
  roles:
     - { role: router_hub_dmvpn }

- hosts: DMVPN_SPOKE
  connection: local
  roles:
     - { role: router_spoke_dmvpn }

- hosts: switch
  connection: local
  roles:
    - { role: switch_vlan }
    - { role: switch_ospf }
    - { role: switch_network_interfaces }
