# Configuration Spoke DMVPN Manchester
- name: 5.0 | {{ inventory_hostname }} | Configure Spoke DMVPN
  ios_config:
    provider: "{{ provider_man }}"
    authorize: yes
    src: "conf_spoke_dmvpn_man.j2"