- name: Create vlan
  ios_vlan:
    vlan_id: 100
    name: test-vlan
    state: present

- name: Add interfaces to VLAN
  ios_vlan:
    vlan_id: 100
    interfaces:
      - GigabitEthernet0/0
      - GigabitEthernet0/1

- name: Check if interfaces is assigned to VLAN
  ios_vlan:
    vlan_id: 100
    associated_interfaces:
      - GigabitEthernet0/0
      - GigabitEthernet0/1

- name: Delete vlan
  ios_vlan:
    vlan_id: 100
    state: absent

#         parents: "interface {{ item.interface }}"
#         match: strict
#       with_items:
#         - { interface : Ethernet0/0, address : "{{ eth_00_ip }} {{ eth_00_mask }}" }
#         - { interface : Ethernet0/1, address : "{{ eth_01_ip }} {{ eth_01_mask }}" }