#-------------------------------------------------------#
# Configuration des interfaces pour le site de bordeaux #
#-------------------------------------------------------#
- name: 0.0 | SYS | Definition du provider
  set_fact:
    provider:
      host: "{{ inventory_hostname }}"
      username: "{{ mgmt_username_bdx }}"
      password: "{{ mgmt_password_bdx }}"
    loop_ip_bdx: "{{loop_ip_bdx}}"
    
  # vars:
  #   mgmt_username_bdx: "{{ vault_mgmt_username }}"
  #   mgmt_password_bdx: "{{ vault_mgmt_password }}"