- name: 1.0 | Create vlan {{ vlan_id_1 }}
  ios_vlan:
    vlan_id: "{{ vlan_id_1 }}"
    name: "{{ vlan_name_1 }}"
    state: present
    provider: "{{ provider }}"
    authorize: yes

- name: 1.1 | Create vlan {{ vlan_id_2 }}
  ios_vlan:
    vlan_id: "{{ vlan_id_2 }}"
    name: "{{ vlan_name_2 }}"
    state: present
    provider: "{{ provider }}"
    authorize: yes

- name: 1.2 | Create vlan {{ vlan_id_3 }}
  ios_vlan:
    vlan_id: "{{ vlan_id_3 }}"
    name: "{{ vlan_name_3 }}"
    state: present
    provider: "{{ provider }}"
    authorize: yes

- name: 1.3 | Create vlan {{ vlan_id_4 }}
  ios_vlan:
    vlan_id: "{{ vlan_id_4 }}"
    name: "{{ vlan_name_4 }}"
    state: present
    provider: "{{ provider }}"
    authorize: yes

#vtp mode transparent
- name: 1.4 | vtp mode
  ios_config:
    provider: "{{ provider }}"
    authorize: yes
    src: "vtp.j2"
