- name: 0.0 | SYS | Definition du provider
  set_fact:
    provider:
      host: "{{ inventory_hostname }}"
      username: "{{ mgmt_username_bdx }}"
      password: "{{ mgmt_password_bdx }}"
  # vars:
  #   mgmt_username: "{{ vault_mgmt_username }}"
  #   mgmt_password: "{{ vault_mgmt_password }}"

- name: 1.1 | IOS {{ inventory_hostname }} | Configure interface Ethernet{{eth_01_id_bdx}}
  ios_config:
    provider: "{{ provider }}"
    authorize: yes
    src: "eth_01_interface_bdx.j2"

- name: 1.2 | IOS {{ inventory_hostname }} | Configure interface Ethernet{{eth_02_id_bdx}}
  ios_config:
    provider: "{{ provider }}"
    authorize: yes
    src: "eth_02_interface_bdx.j2"

- name: 1.0 | {{ inventory_hostname }} | Configure interface Loopback {{loop_number_bdx}}
  ios_config:
    provider: "{{ provider }}"
    authorize: yes
    src: "loopback_interface_bdx.j2"