####################
# Site de bordeaux #
####################

# Credentials #
#-------------#
mgmt_username_bdx: cisco
mgmt_password_bdx: cisco

mgmt_username_tls: cisco
mgmt_password_tls: cisco

mgmt_username_oxf: cisco
mgmt_password_oxf: cisco

mgmt_username_man: cisco
mgmt_password_man: cisco

# Loopback @ #
#------------#
loop_ip_bdx: 33.33.33.33
loop_ip_tls: 31.31.31.31
loop_ip_oxf: 186.186.186.186
loop_ip_man: 161.161.161.161