#------------------------------------------------#
# Configuration ospf pour le routeur de bordeaux #
#------------------------------------------------#
- name: 2.0 | IOS {{ inventory_hostname }} | Configure OSPF BDX
  ios_config:
    provider: "{{provider_bdx}}"
    authorize: yes
    src: "ospf_setting_bdx.j2"